apiVersion: v1
kind: Service
metadata:
  name: book-server
  labels:
    app: book-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: book-server
